'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const tool=require('./tool.cjs'),core=require('./src/research-services.cjs'),{validateEnvelope}=require('./src/research-result-validation.cjs'),{parseInput,localizedNumber}=require('./src/research-input.cjs'),{researchCopy,researchLocales,keys}=require('./src/research-copy-authored.cjs'),{researchScope}=require('./src/research-scopes-authored.cjs'),{researchDocumentCopy}=require('./src/research-document-copy-authored.cjs'),{createProviderLock}=require('./src/research-provider-lock.cjs');
const rows=[],record=async(name,fn)=>{try{await fn();rows.push({name,pass:true});}catch(error){rows.push({name,pass:false,error:error.message});}},sample=require('./example.json'),spec=tool.specification;
const keepAlive=setInterval(()=>{},1000);let temporary;
(async()=>{
 await record('fixed public example schema',()=>assert.deepEqual(tool.validate(sample),sample));
 await record('provider-specific bounded request deadlines',()=>{assert.deepEqual(core.REQUEST_TIMEOUT_MS,{'www.cbioportal.org':20000,'rest.ensembl.org':60000,'biit.cs.ut.ee':20000,'tools-cluster-interface.iedb.org':90000});for(const [host,limit]of Object.entries(core.REQUEST_TIMEOUT_MS)){assert.equal(core.requestTimeoutMs(host,120000),limit);assert.equal(core.requestTimeoutMs(host,1500),1500);}});
 await record('aggregate timeout cannot expand',()=>{assert.throws(()=>core.createService({workflowTimeoutMs:120001}),e=>e.code==='UPSTREAM_POLICY');assert.throws(()=>core.requestTimeoutMs('rest.ensembl.org',0),e=>e.code==='UPSTREAM_TIMEOUT');assert.equal(spec.transportLimits.workflowMs,120000);assert.equal(spec.transportLimits.retry,false);});
 for(const [name,bad]of [['unknown-key',{...sample,patientName:'refused'}],['confirmation',{...sample,publicResearchData:false}],['null',null],['array',[]],['missing',{}]])await record('input refusal '+name,()=>assert.throws(()=>tool.validate(bad)));
 const result=await tool.create({offline:true}).execute(sample);await record('complete response contract',()=>assert.equal(validateEnvelope(tool.id,result),true));
 await record('implementation identity',()=>assert.equal(result.implementationVersion,spec.implementationVersion));await record('provider/source identity',()=>assert.deepEqual(result.sources,spec.sources));
 await record('expected official response checks',()=>{if(tool.id==='cbioportal'){assert.equal(result.version.portal,'v7.1.2');assert.equal(result.rows.length,25);assert.ok(result.rows.every(r=>r.gene==='TP53'));assert.equal(result.summary.distinctSamplesOnThisPage,new Set(result.rows.map(r=>r.sampleId)).size);assert.equal(result.pagination.totalRecords,null);}else if(tool.id==='ensembl-vep'){assert.equal(result.version.ensembl,116);assert.equal(result.version.rest,'15.12');assert.equal(result.version.assembly,'GRCh38');assert.equal(result.rows[0].consequence,'missense_variant');assert.ok(result.rows[0].transcripts.some(t=>t.geneSymbol==='BRAF'&&t.aminoAcids==='V/E'&&t.proteinStart===600));}else if(tool.id==='gprofiler-gost'){assert.equal(result.version.gProfiler,'e114_eg62_p19_27110d83');assert.equal(result.version.goDoi,'10.5281/zenodo.18422732');assert.equal(result.rows[0].termId,'GO:0014809');assert.equal(result.rows[0].precision,.8);assert.equal(result.rows[0].recall,.8);}else{assert.equal(result.rows.length,10);assert.equal(result.version.method,'smm-1.0');assert.equal(result.version.runtimeModelHash,null);const starts=new Set();for(const row of result.rows){assert.equal(row.end,row.start+8);assert.equal(row.peptide,sample.sequence.slice(row.start-1,row.end));starts.add(row.start);}assert.deepEqual([...starts].sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9,10]);assert.equal(result.rows.find(r=>r.start===2).ic50Nanomolar,1286.92);}});
 for(const [name,mutate]of [['version',r=>r.implementationVersion='old'],['rights',r=>delete r.rights],['unexpected',r=>r.patientName='refused'],['source',r=>r.sources=['http://example.invalid']],['time',r=>r.retrievedAt='not-a-time'],['identity',r=>r.toolId='unknown'],['numeric',r=>{if(tool.id==='iedb-analysis-resource')r.rows[0].ic50Nanomolar=Infinity;else if(tool.id==='gprofiler-gost')r.rows[0].adjustedP=Infinity;else r.rows[0].position=Infinity;}]])await record('response refusal '+name,()=>{const r=JSON.parse(JSON.stringify(result));mutate(r);assert.equal(validateEnvelope(tool.id,r),false);});
 const invalids=tool.id==='cbioportal'?[{genes:[]},{genes:['TP53','TP53']},{page:0},{page:101},{genes:['TP53<script>']}]:tool.id==='ensembl-vep'?[{assembly:'GRCh37'},{variants:[]},{variants:[{chromosome:'7',position:1.5,reference:'A',alternate:'T'}]},{variants:[{chromosome:'7',position:1,reference:'A',alternate:'A'}]},{variants:[{chromosome:'7',position:1,reference:'AA',alternate:'T'}]}]:tool.id==='gprofiler-gost'?[{sources:['KEGG']},{threshold:0},{threshold:NaN},{correction:'none'},{background:[]}]:[{sequence:'SLYNTVAT'},{sequence:'SLYNTVATX'},{sequence:'slyntvatly'},{sequence:'A'.repeat(201)},{allele:'HLA-B*07:02'}];for(const [i,bad]of invalids.entries())await record('bounds '+i,()=>assert.throws(()=>tool.validate({...sample,...bad})));
 for(const locale of researchLocales){await record(locale+' authored interface/scope/rights/documentation',()=>{const c=researchCopy(locale),d=researchDocumentCopy(tool.id,locale);assert.equal(Object.keys(c).length,keys.length);assert.ok(Object.values(c).every(text=>typeof text==='string'&&text.trim()));assert.ok(researchScope(tool.id,locale).trim());assert.ok(d.rights&&d.review&&d.methodDisclosure);const doc=spec.docs.find(row=>row.locale===locale);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,doc.path))).digest('hex'),doc.sha256);});await record(locale+' decimal/digit conditional',()=>{const v=['pt-BR','es','fr','de','it'].includes(locale)?'0,05':locale==='ar'?'٠٫٠٥':locale==='hi'?'०.०५':'0.05';assert.equal(localizedNumber(v,locale),.05);const p=locale==='ar'?'١٤٠٧٥٣٣٣٦':locale==='hi'?'१४०७५३३३६':'140753336';assert.equal(parseInput(core.ID.vep,{variants:'7 '+p+' A T',confirm:true},locale).variants[0].position,140753336);});}
 const request=(body,extra={})=>new Request('http://127.0.0.1:3057/execute',{method:extra.method||'POST',headers:{Origin:'http://localhost:3057','Content-Type':'application/json',...extra.headers},...((extra.method||'POST')==='POST'?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});
 for(const [name,req,status]of [['foreign origin',request(sample,{headers:{Origin:'https://example.invalid'}}),403],['cross-site',request(sample,{headers:{'Sec-Fetch-Site':'cross-site'}}),403],['wrong media',request(sample,{headers:{'Content-Type':'text/plain'}}),415],['encoding',request(sample,{headers:{'Content-Encoding':'gzip'}}),415],['body cap',request(sample,{headers:{'Content-Length':'65537'}}),413],['bad length',request(sample,{headers:{'Content-Length':'five'}}),413],['malformed JSON',request('{'),422],['wrong method',request(null,{method:'GET'}),405]])await record('HTTP refusal '+name,async()=>assert.equal((await tool.create({offline:true}).handler(req)).status,status));
 await record('HTTP offline response',async()=>assert.equal((await tool.create({offline:true}).handler(request(sample))).status,200));
 await record('upstream timeout is explicit',async()=>{const service=core.createService({workflowTimeoutMs:1000,fetchImpl:async(u,o)=>await new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(Error('timeout'),{name:'AbortError'})),{once:true}))});await assert.rejects(service.execute(tool.id,sample),e=>e.code==='UPSTREAM_TIMEOUT');});
 await record('wrong provider version/shape refuses response',async()=>{const fetchBase=tool.fixtureFetch();await assert.rejects(core.createService({fetchImpl:async(u,o)=>{const r=await fetchBase(u,o);if(String(u).includes('iedb.org'))return new Response('wrong\tcolumns\n1\t2\n',{headers:{'Content-Type':'text/tsv'}});return new Response('{"unexpected":true}',{headers:{'Content-Type':'application/json'}});}}).execute(tool.id,sample));});
 const base=process.env.ELUCENIA_RESEARCH_TEST_DIRECTORY||os.tmpdir();assert.ok(path.isAbsolute(base));fs.mkdirSync(base,{recursive:true});temporary=fs.mkdtempSync(path.join(base,'elucenia-research-test-'));
 await record('shared lock and interrupted IEDB cooldown',async()=>{let now=1000000;const a=createProviderLock(temporary,{now:()=>now}),b=createProviderLock(temporary,{now:()=>now});const token=await a.acquire('iedb');assert.ok(token);assert.equal(await b.acquire('iedb'),null);await a.release(token,{code:'UPSTREAM_TIMEOUT'});now+=1001;assert.equal(await b.acquire('iedb'),null);assert.ok((await b.inspect('iedb')).budget.cooldownUntil>=1300000);now=1300001;const next=await b.acquire('iedb');assert.ok(next);await b.release(next);});
 const out={schema:'elucenia-research-offline-tests-v1',id:tool.id,implementationVersion:spec.implementationVersion,tests:rows.length,passed:rows.filter(r=>r.pass).length,failed:rows.filter(r=>!r.pass).length,scope:'Offline replays of captured official public/synthetic API responses, exact request/response/version/bounds/locale/timeout/shared-lock contracts. No network, browser, private portal/session or independent provider-model/clinical validation.',rows};
 if(process.argv.length>2){assert.equal(process.argv.length,4);assert.equal(process.argv[2],'--record');fs.writeFileSync(process.argv[3],JSON.stringify(out,null,2)+'\n',{flag:'wx'});}console.log(JSON.stringify(out));if(out.failed)process.exitCode=1;
})().catch(error=>{console.error(JSON.stringify({error:error.message}));process.exitCode=1;}).finally(()=>{clearInterval(keepAlive);if(temporary){const real=fs.realpathSync(temporary);assert.equal(real,path.resolve(temporary));assert.ok(path.basename(real).startsWith('elucenia-research-test-'));fs.rmSync(real,{recursive:true});}});
